version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=zuza
      - MYSQL_PASSWORD=muza
      - MYSQL_ROOT_PASSWORD=muza
      - MYSQL_DATABASE=scoala